### ISSUE TITLE
Using Enum in class arguments.

### ISSUE THREAD

**Issue by QLutz** [illuin-tech/configue#26]
As reproducible using [this repo](https://github.com/QLutz/redesigned-lamp), trying to instantiate a class
```python
class MyClass:
    """
    Sample class having a sole Enum-typed attribute
    """
    def __init__(self, choice: Choice):
        self.choice = choice

    def print_choice(self):
        """
        Print the Enum attribute of the object
        """
        print(self.choice)
```

where Choice is defined by:

```python
class Choice(Enum):
    """
    Minimal Enum class
    """
    A = "a"
    B = "b"
```

with the following `yml`:
```yml
my_object:
  (): stub.MyClass
  choice: !ext stub.Choice.A
```

raises `cannot find module 'stub.Choice'` (both `MyClass` and `Choice` being located in `stub.py`) with configue 4.1.1 (Python 3.9, MacOS /w M1)

Is there already a way to use Enum keys with Configue?

Thanks in advance.

**Comment by QLutz** [comment]
Solved by turning the `yml` into 
```yml
choice_enum: !ext stub.Choice
my_object:
  (): stub.MyClass
  choice: !cfg choice_enum.A
```
